export const sample_cakes = [
  {
    id: "1",
    name: "Strawberry Cheesecake",
    cookTime: "2-4hrs",
    price: 900,
    favorite: false,
    origins: ["With loaded Strawberries"],
    stars: 4.5,
    imageUrl: "cake-1.jpg",
    tags: ["Cakes", "Strawberry", "Dessert"],
  },
  {
    id: "2",
    name: "Chocolate Truffle",
    price: 1200,
    cookTime: "2-3hrs",
    favorite: true,
    origins: ["Chocolate coated"],
    stars: 5,
    imageUrl: "cake-2.jpg",
    tags: ["RichCake", "Dessert"],
  },
  {
    id: "3",
    name: "Macroons",
    price: 200,
    cookTime: "2hrs",
    favorite: false,
    origins: ["Kids Favourite"],
    stars: 4.2,
    imageUrl: "cake-3.jpg",
    tags: ["Cookies", "Snack"],
  },
  {
    id: "4",
    name: "Blackberry cheesecake",
    price: 450,
    cookTime: "3-4hrs",
    favorite: true,
    origins: ["Delicious pastry"],
    stars: 4.7,
    imageUrl: "cake-4.jpg",
    tags: ["Pastry", "Dessert"],
  },
  {
    id: "5",
    name: "Donuts",
    price: 20,
    cookTime: "4-5hrs",
    favorite: true,
    origins: ["Flavoured donuts "],
    stars: 4.9,
    imageUrl: "cake-5.jpg",
    tags: ["Chocolate", "Dessert", "Birthday"],
  },
  {
    id: "6",
    name: "Chocoalte cupcake (12)",
    price: 600,
    cookTime: "1-2hrs",
    favorite: false,
    origins: ["A little sweet"],
    stars: 4.5,
    imageUrl: "cake-6.jpg",
    tags: ["Dessert"],
  },
];

export const sample_tags = [
  { name: "All", count: 4 },
  { name: "Cakes", count: 1 },
  { name: "Cupcakes", count: 1 },
  { name: "Cookies", count: 1 },
  { name: "Pastry", count: 1 },
  { name: "Chocolate", count: 2 },
  { name: "Dessert", count: 3 },
  { name: "Snack", count: 1 },
];

export const sample_users = [
  {
    id: 1,
    name: "John Doe",
    email: "john@gmail.com",
    password: "12345",
    address: "Toronto On",
    isAdmin: false,
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "jane@gmail.com",
    password: "12345",
    address: "Shanghai",
    isAdmin: true,
  },
];
